### ISSUE TITLE
Reporting installed libraries by python pip

### ISSUE THREAD

**Issue by evandrocoan** [lemurheavy/coveralls-public#1155]
I installed both `codecov` and `coveralls` in my project:
1. https://codecov.io/gh/evandrocoan/ContextFreeGrammars
1. https://coveralls.io/github/evandrocoan/ContextFreeGrammars?branch=master

While code `codecov` correctly report only my project files:
![image](https://user-images.githubusercontent.com/5332158/42416201-7e3514ec-823e-11e8-9e2c-a3a68cfdd256.png)

`coveralls` also report system libraries installed by `python pip` as from my project:
![image](https://user-images.githubusercontent.com/5332158/42416185-0778a148-823e-11e8-9fcc-0d19af8ae4dc.png)

This is my `travis.yml`:
```yml
matrix:
    include:
        - os: linux
          language: python
          python: 3.6

        - os: osx
          language: generic


before_install:

    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            pip install codecov;
            pip install python-coveralls;
            pip install -r requirements.txt;
      fi

    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew update;
            brew upgrade python;
            pip3 install --user -r requirements.txt;
      fi


script:

    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            coverage run source/unit_tests.py;
            codecov;
            coveralls;
      fi

    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            python3 source/unit_tests.py;
      fi


notifications:
    email: false
```
