### ISSUE TITLE
Recent builds not updating when CircleCI Workflow job parallelism >1

### ISSUE THREAD

**Issue by ain** [lemurheavy/coveralls-public#1191]
Recent builds on repository page are not updating, e.g.:

![screen shot 2018-09-26 at 13 21 52](https://user-images.githubusercontent.com/370576/46076908-482a0e80-c18f-11e8-8981-73d8e6f0cc5f.png)

vs the following in _Latest updates_ for the same repo:

![screen shot 2018-09-26 at 13 24 31](https://user-images.githubusercontent.com/370576/46076991-963f1200-c18f-11e8-8b9c-f9e0598833ca.png)

When parallelism is removed, everything works as expected.

**Comment by bytewalls** [comment]
@ain,

Sorry for the delay in getting back to you, I now have a solution for you. There are a couple of issues encountered with using workflows vs the old jobs, one is that your Workflow (the entire build, and what Coveralls calls a build) is now multiple builds on CircleCI. In order to get around this, inline for your command that executes coverage you need to set `CIRCLE_BUILD_ID=$CIRCLE_WORKFLOW_ID` over time we will work to get this out in our integration libraries, but we need to use the workflow id instead of the build id as the unique identifier to combine your build. (ex run command might be `CIRCLE_BUILD_NUM=$CIRCLE_WORKFLOW_ID bundle exec rspec`) We don't want to override this environment variable everywhere, hence why doing it inline.

The second issue, as you have pointed out in previous tickets is that webhooks don't work quite like you would expect, they execute every time a build finishes, not when the whole workflow finishes. In order to solve this issue within the constaints of circle, you will need to add a workflow build which is dependent on all your coverage reporting builds which manually hits our parallel build endpoint. 

Here is an example of the job I build to run this manual curl hit, note the docker image type doesn't matter, you just need curl:
```
parallel-finished:
    environment:
      COVERALLS_REPO_TOKEN: << repo token here >>
    docker:
      - image: circleci/ruby
    steps:
      - run: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"
```

And here is an example of how my workflow was setup, note `e2e` and `unit-and-integration` both report coverage, and as such I need to require them before reporting finished:
```
workflows:
  run-tests:
    jobs:
      - config
      - integration-and-unit:
          requires:
            - config
      - e2e:
          requires:
            - config
      - parallel-finished:
          requires:
            - integration-and-unit
            - e2e
```

**Comment by ain** [comment]
Thanks a lot @bytewalls, I'll test and report back with the results.

**Comment by afzalSH-moneysmart** [comment]
We have the below structure for our new project

```
.
├── LICENSE.txt
├── README.md
└── handlers
            ├── handler_1
            ├── handler_2
            ├── handler_3
             .
             .
             .
```

The handlers are ruby gems and I run their rspec tests in a workflow, each job in the workflow handling a particular gem's tests. The builds run fine but I just can't manage to hit coveralls.

In my circle ci project environment vars, I have `COVERALLS_PARALLEL = true` and after following this answer below is my circleci config;

```
version: 2.1

commands:
  build_handler:
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            CIRCLE_BUILD_ID=$CIRCLE_WORKFLOW_ID bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

jobs:
  sg_ti_allianz_url_builder:
    working_directory: ~/repo/handlers/sg_ti_allianz_url_builder
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - build_handler

  sg_ti_aviva_url_builder:
    working_directory: ~/repo/handlers/sg_ti_aviva_url_builder
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - build_handler

  sg_finsense_api_handler:
    working_directory: ~/repo/handlers/sg_finsense_api_handler
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - build_handler

  update_coveralls:
    environment:
      COVERALLS_REPO_TOKEN: <our_repo_token>
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - run: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"

workflows:
  handler_builds:
    jobs:
      - sg_ti_allianz_url_builder
      - sg_ti_aviva_url_builder
      - sg_finsense_api_handler
      - update_coveralls:
          requires:
            - sg_ti_allianz_url_builder
            - sg_ti_aviva_url_builder
            - sg_finsense_api_handler
```

All the gems have the below in their `spec_helper.rb`s

```
require 'coveralls'

Coveralls.wear!
```

Now I'm new to all of ruby, circleci and coveralls

All the jobs run in their own containers and I'm not even sure how everything connects.

But if you see a way you could help me out, please do.

Below is the response I get from the curl command
```
#!/bin/bash -eo pipefail
curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_WORKFLOW_ID&payload[status]=done"
{"error":"No build matching CI build number <build-number> found"}
```
