### ISSUE TITLE
coveralls & circleci Updates are ignored

### ISSUE THREAD

**Issue by AndreasAZiegler** [lemurheavy/coveralls-public#1285]
I have a github repository (https://github.com/AndreasAZiegler/poly-exploration) for which I use circleci and coveralls among other tools.

So far I only go coveralls working if I changed the token and updated it within ```.coveralls.yml```. Any updates are ignored.

I use the following commands in the circleci to run coveralls (You can also look in the repo .circleci/config.yml):

```
version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y python-pip python-yaml git curl cmake gcc g++ && pip install cpp-coveralls'
      - run:
          name: Build
          command: 'cd build && make'
      - run:
          name: Test
          command: 'cd build && make test'
      - run:
          name: Coveralls
          command: /usr/local/bin/coveralls --exclude libs --exclude build --exclude test --exclude /usr/include/c++ --exclude /usr/include/boost --gcov-options '\-lp'
```
