### ISSUE TITLE
GitHub build status takes very long time to come through (parallel builds)

### ISSUE THREAD

**Issue by reececomo** [lemurheavy/coveralls-public#1407]
* We set `COVERALLS_PARALLEL=true`
* We upload three parallel reports within a couple minutes of each other.
* We update the we build status manually with `curl -k $COVERALLS_ENDPOINT/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$BUILD_NUMBER&payload[status]=done"`
* Coveralls merges these results and we can see the values on the Coveralls interface immediately 👍 

However...

We're finding the GitHub build status takes > 10 minutes to arrive, and in a couple cases, looks like it never arrived at all.

Very confused here - can you offer any guidance?

**Comment by jfarrell** [comment]
we are also seeing an increase in build status reporting back to Github from Coveralls. After Coveralls has received the coverage report and the build has finished we have seen upwards of 30m in some cases of the successful notification reaching back to Github

**Comment by reececomo** [comment]
Yep just noticed this is also happening on some of our non-parallel repos too.

**Comment by glennpratt** [comment]
Seeing the same thing here across several private repos. Emailed support with no response.

**Comment by reececomo** [comment]
We just switched our org over from CodeCov, I guess we'll have to switch back 😞

**Comment by danadaldos** [comment]
Yep also seeing 30 minute build times on CircleCI (when CircleCI is correctly configured for parallel builds)

![Pipelines](https://user-images.githubusercontent.com/10788889/76685353-924bbd80-65d8-11ea-9b2d-5269389d5a82.png)

**Comment by narwold** [comment]
We're seeing this same issue. This presents a major workflow challenge. Any status update on this?

**Comment by danadaldos** [comment]
@narwold 
> We're seeing this same issue. This presents a major workflow challenge. Any status update on this?

Ours actually cleared-up at some point. Here's our CircleCI configuration (edited down to relevant parts):

Unit test step:
```
  test:
    <<: *testing_container_config
    parallelism: 7
    steps:
          ... [workspace setup and cache restore] ...
          
      - run:
          name: Run Non-Feature Tests
          command: |
            circleci tests glob "test/**/*_test.exs" | circleci tests split --split-by=timings > /tmp/tests-to-run
            echo ""
            echo "************ Test files in this container ***************"
            cat /tmp/tests-to-run
            echo ""
            mix coveralls.circle --parallel $(cat /tmp/tests-to-run) --exclude feature
```

Run feature tests step:
```
  test_features:
    <<: *testing_container_config
    parallelism: 10
    steps:
      ... [workspace setup and cache restore] ...

      - run:
          name: Run Feature Tests
          command: |
            ...
            mix coveralls.circle --parallel --timeout=90000 $(cat /tmp/tests-to-run)
```            

Notify Coveralls step:
```
  notify_coveralls:
    docker:
      - image: cimg/base:2020.01
    steps:
      - *attach_workspace
      - run: |
          curl "https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN" \
            -d "payload[build_num]=$CIRCLE_WORKFLOW_WORKSPACE_ID&payload[status]=done"
          echo $CIRCLE_WORKFLOW_WORKSPACE_ID
          exit 0
```

Workflow:
```
workflows:
  build_and_test:
    jobs:
      - build
      - check_formatted:
          requires:
            - build
      - check_for_unused_dependencies:
          requires:
            - build
      - credo:
          requires:
            - build
      - dialyzer:
          requires:
            - build
      - lint:
          requires:
            - build
      - test:
          context: slack-secrets
          requires:
            - build
      - test_features:
          context: slack-secrets
          requires:
            - build
      - notify_coveralls:
          requires: [test, test_features]
          ```
