### ISSUE TITLE
Option to configure thresholds in Github CI workflows

### ISSUE THREAD

**Issue by pnoltes** [lemurheavy/coveralls-public#1431]
I would be nice to be able to configure coveralls thresholds directly form the Github CI configuration instead of the coveralls project settings. 

This specifically useful for project that cannot grant read access to their organisation (i.e. Apache GitHub projects) 

For example:
```yaml
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        threshold-for-failure: 90
        decrease-threshold-for-failure: 0.5
```
