### ISSUE TITLE
Specify thresholds via coveralls.yml file

### ISSUE THREAD

**Issue by shibumi** [lemurheavy/coveralls-public#1455]
Hi,
is it possible to set coverage thresholds via coveralls.yml file?
It would be nicer if it would be possible to control this in the repository itself.
I am using travis + coveralls.

**Comment by afinetooth** [comment]
Hi @shibumi,

Try adding the following to your `coveralls.yml`:

```
status:
  change_threshold: 5
  api:
    fail_threshold: 90
```

Just change the values and I do believe that should do it. If not let me know.
