### ISSUE TITLE
Coveralls gives 422 though GitHub token has been set

### ISSUE THREAD

**Issue by mristin** [lemurheavy/coveralls-public#1493]
Hi,
I am getting a 422 error though GitHub token has been correctly set. Please see this build for more information:
https://github.com/Parquery/logthis/pull/5/checks?check_run_id=1249591770

The error message is:
```
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/coveralls/api.py", line 206, in wear
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/coveralls/api.py", line 209, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

The GitHub workflow is fairly simple and worked on other projects:
```
name: Check-pull-request

on: [pull_request]

jobs:
  Execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .[dev]
          pip3 install coveralls

      - name: Run checks
        run: ./precommit.py

      - name: Upload coverage to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls
```

Thank you in advance for your help!

**Comment by afinetooth** [comment]
Hi @mristin, a quick response for now:

I noticed the line `uses: coverallsapp/github-action@master` missing from your Github workflow, which is what invokes the Coveralls Github Action. Can you please add that and re-run to see if you get different behavior?

Also, I have seen this 422 error recently with Github Actions using [coveralls-python](https://github.com/coveralls-clients/coveralls-python) here:
https://github.com/lemurheavy/coveralls-public/issues/1492

So maybe we're having an issue with that integration. Worth checking out their issues to see.

Let me know if you still have trouble after checking those steps.

**Comment by mristin** [comment]
Hi @afinetooth ,
Do you know how I can obtain the lcov file? Please see the error in the run: https://github.com/Parquery/logthis/pull/5/checks?check_run_id=1287780412

**Comment by afinetooth** [comment]
Hi @mristin, can you please share the following?

1. What code coverage tooling are you using in your project? For example: [coverage.py](https://coverage.readthedocs.io/en/latest/)?
2. What coveralls integration are you using? For example: [coveralls-python](https://github.com/coveralls-clients/coveralls-python)? [python-coveralls](https://github.com/z4r/python-coveralls)?

I ask because (1) generates your coverage report (which is what we want in LCOV format). The relevant docs should walk you through how to generate a coverage report from each run of your test suite. 

Also asking because setting up either of the integrations in (2) should cover how to get your coverage report in LCOV format (if it's not already) and where to place it so the integration can find it and upload it to the coveralls API.

Right now, I don't see any builds on your project, so I can see you're still setting up.

**Comment by afinetooth** [comment]
@mristin on the chance you're using [coveralls-python](https://github.com/coveralls-clients/coveralls-python), here are three (3) closed issues with that same stacktrace:

1. https://github.com/coveralls-clients/coveralls-python/issues/219
2. https://github.com/coveralls-clients/coveralls-python/issues/211
3. https://github.com/coveralls-clients/coveralls-python/issues/206

Those might give you more insight than we can provide coming from the service side.

Also, here's some [documentation on calling coveralls in verbose / debug mode with coveralls-python](https://coveralls-python.readthedocs.io/en/latest/troubleshooting.html?highlight=debug), which will add debug output to CI stdout and show you what you're trying to send to the coveralls API:

**Comment by mristin** [comment]
Hi @afinetooth ,

> What code coverage tooling are you using in your project? For example: coverage.py?

As you can see from https://github.com/Parquery/logthis/pull/5/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R47, we are using coverage (https://pypi.org/project/coverage/).

I suppose that is indeed coverage.py (judging by the title at https://coverage.readthedocs.io/en/coverage-5.3/)?

> What coveralls integration are you using? For example: coveralls-python? python-coveralls?

I set up only the action coverallsapp/github-action@master (https://github.com/Parquery/logthis/pull/5/files#diff-d57a8f8916c02e1b4c666d60987fd7a9cf5525433bd8c01c32a51817285153d2R28).

**Comment by TheKevJames** [comment]
@mristin it looks like you may be running into TheKevJames/coveralls-python#252; I recommend checking if adding `--service=github` solves your problem. Eg. that would mean replacing the last step of your job with:
```yaml
      - name: Upload coverage to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
```
