### ISSUE TITLE
Mixed coverage report in same function

### ISSUE THREAD

**Issue by sebastianrath** [lemurheavy/coveralls-public#1533]
I recently implemented coveralls support in my project. Can anyone explain me how line `447` is marked as not covered, where the next line `448` is fine? My repo has a variety of locations with this, and I can't explain how the coverage can have these mixed results without a condition.

<img width="786" alt="Screen Shot 2021-02-27 at 2 01 05 AM" src="https://user-images.githubusercontent.com/12844423/109378335-a8ad6080-789f-11eb-9c2a-f8025ca84d13.png">

```Background Information: My workflow has two jobs (macOS + Windows), and both contain the coveralls github action.```

```
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

**Coveralls.io Report:**
https://coveralls.io/builds/37498339/source?filename=src%2Frepository.ts#L442

**Location in Repo**
https://github.com/Snowtrack/SnowFS/blob/18c5dfe0841b8ffc02d786aa11290d80b8cb12d7/src/repository.ts#L442

**GitHub workflow**
https://github.com/Snowtrack/SnowFS/blob/main/.github/workflows/workflow.yml
