### ISSUE TITLE
Coveralls Status Check does not appear in pull request

### ISSUE THREAD

**Issue by PraveenKumar205** [lemurheavy/coveralls-public#1591]
Coveralls Coverage gets updated for every commit in coveralls.io but the Status check does not appear in the github pull request.

![0763C409-5551-4F6D-8F77-749510F96C94](https://user-images.githubusercontent.com/65845949/138894189-8a87c404-d90a-4bf9-bae5-68896cd7e20b.png)

<img width="838" alt="Screenshot 2021-10-26 at 7 35 26 PM" src="https://user-images.githubusercontent.com/65845949/138895581-f27cf91c-5056-4173-af44-b6663612cf27.png">

It was working fine in my own repository, But it was not working in private repository.

**Comment by afinetooth** [comment]
@PraveenKumar205 can you please share:

1. The coveralls URL for the project / repo; and
2. The URL for any PR builds where you're seeing this behavior.

**Comment by PraveenKumar205** [comment]
sure @afinetooth ,
1. Coveralls Url: `https://coveralls.io/github/shopuptech`
2. PR build:  `https://github.com/shopuptech/sr_service/runs/3996630815?check_suite_focus=true`

**Comment by afinetooth** [comment]
Hi @PraveenKumar205. The issue with this repo appears to be that you haven't sent any builds of type **pull_request** to coveralls.

Per your build history:
`https://coveralls.io/repos/350219/builds`

![Screen Shot 2021-10-28 at 1 40 15 PM](https://user-images.githubusercontent.com/918667/139332222-dd74b35e-160e-4cfa-b995-ed1142f8b9db.png)

Note that the value in the TYPE column for all builds there is **push** (with none being **pull_request**).

I believe that if you are configured the same as you are for your other projects, and you start sending us PR builds on [shopuptech/sr_service](https://coveralls.io/github/shopuptech/sr_service), you'll start receiving status updates on them.

If not, let me know. 

If you think you _are_ building **pull_request** builds in CI and the [Coveralls API](https://docs.coveralls.io/api-reference) is not _recognizing_ them as such, you'll want to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) on your integration and examine the JSON you're sending to the [Coveralls API](https://docs.coveralls.io/api-reference) in the debug info added to your build logs.

Presuming you're using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), the way to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) is to add the following environment variable to your GHA config yaml so that it's available to the coveralls step(s):
`NODE_COVERALLS_DEBUG=1`

(_The `NODE_` part is there because the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under-the-hood._)

If you're concerned about security with your private repo, feel free to email us at support@coveralls.io and mention this issue.

**Comment by PraveenKumar205** [comment]
Hi @afinetooth  I tried the type as **pull_request** for the same repository and still I was not able to see the status check.

Even if thats the case its working fine with type **push** my repository 
`https://coveralls.io/github/PraveenKumar205/example

<img width="853" alt="Screenshot 2021-10-29 at 9 26 45 PM" src="https://user-images.githubusercontent.com/65845949/139466061-a86aff4f-1379-4542-adfb-305791b13b40.png">

```
- name: Send coverage
        env:
          NODE_COVERALLS_DEBUG: 1
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          cd GoLang/src/github.com/voonik/sr_service
          goveralls -v -coverprofile=./cover.text -service=github
```
I tried `-v` flag and `NODE_COVERALLS_DEBUG` env variable as well but I am not able to see any difference in build logs.

**Comment by afinetooth** [comment]
Hi @PraveenKumar205. 

Re: building and sending PRs to coveralls, I should have clarified that it should happen automatically if you're using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) and you enable **pull_request** builds with the **on:** parameter, per the [standard usage example](https://github.com/marketplace/actions/coveralls-github-action#standard-example).

```
on: ["push", "pull_request"]
```

If you're not using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) and not telling GHA to build **pull_requests** with **on:**, then to make the [Coveralls API](https://docs.coveralls.io/api-reference) recognize your builds as **pull_requests**, you'll want to pass a value for the **service_pull_request** parameter (in the JSON body attached to your post), per the [Coveralls API Reference](https://docs.coveralls.io/api-reference).

But you're right, any type of build can receive status updates at Github, and that further supports my belief that you'll start getting them for your **pull_request** builds as soon as you start sending those.

Please try the:

```
on: ["push", "pull_request"]
```

Param in your GHA config yaml to do that.

(Or the other steps I mention if that doesn't work.)

> I tried -v flag and NODE_COVERALLS_DEBUG env variable as well but I am not able to see any difference in build logs.

That indicates you may not be using the official [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), but another GHA-based integration for coveralls.

Can you share what that is? The easiest way will be to send your full config yaml.

Again, if there's anything sensitive there, please email us at support@coveralls.io and mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1591).

**Comment by PraveenKumar205** [comment]
Hi @afinetooth ,
As you can see in the below screenshot some of the builds were type  **pull_request**.
coveralls url: `https://coveralls.io/repos/350219/builds`

<img width="1013" alt="Screenshot 2021-10-30 at 1 52 59 PM" src="https://user-images.githubusercontent.com/65845949/139525788-826f537a-8860-47a7-8aec-92ac0759ceb7.png">

<img width="856" alt="Screenshot 2021-10-30 at 2 00 34 PM" src="https://user-images.githubusercontent.com/65845949/139526028-b9531bc8-7f92-47a3-917a-35d81c26933c.png">

This is the complete config yaml

```
name: Golang Unit Testing

on: ["push", "pull_request"]

env:
  SOURCE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  GOPRIVATE: github.com/voonik

jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    services:
      # How to use Mysql
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      # How to use Redis
      redis:
        image: redis
        ports:
        - 6379/tcp

    steps:  
      - name: Setup Env Vars and work dir
        run: |
          test -d "GoLang/src/github.com/voonik/sr_service" || mkdir -p "GoLang/src/github.com/voonik/sr_service"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: GoLang/src/github.com/voonik/sr_service

      # - id: files
      #   uses: jitterbit/get-changed-files@v1
      # - run: |
      #    echo ${{ steps.files.outputs.added_modified }}

      - name: Install SSH keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "Add known public keys of github here"

      - name: Verify MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python-dev nginx-extras pkg-config cmake libxrender1 libmysqlclient-dev ncurses-dev gettext flex bison autoconf binutils-doc redis-tools vim nfs-common jq bc
          mysql --host 127.0.0.1 --port 33306 -uroot -ppassword -e "SHOW GRANTS FOR 'root'@'localhost'"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port 33306 -uroot -ppassword mysql

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'

      - name: Create DB
        env:
          ENV: test
        run: |
          touch create_db.sql
          echo "create database sr_test;" >> create_db.sql
          mysql --host 127.0.0.1 --port 33306 -uroot -ppassword  < create_db.sql

      - name: Run tests
        env:
          ENV: test
        run: |
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          export PATH=$PATH:GoLang/bin
          cd GoLang/src/github.com/voonik/sr_service
          go mod download
          go get -u github.com/jstemmer/go-junit-report
          go get github.com/mikefarah/yq/v4
          bash run_tests.sh
          #bash run_tests.sh ${{ steps.files.outputs.added_modified }}

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          NODE_COVERALLS_DEBUG: 1
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          cd GoLang/src/github.com/voonik/sr_service
          goveralls -v -coverprofile=./cover.text -service=github

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/GoLang/src/github.com/voonik/sr_service/*.xml'
```
      
BTW I am using goveralls here. Will it be a problem?

Thanks in advance.
