### ISSUE TITLE
Branch is only displaying master and badge does not update

### ISSUE THREAD

**Issue by ddold** [lemurheavy/coveralls-public#1594]
Testing out Coveralls with a private repo I am noticing some inconsistencies. 
First off the build number was a uid, but turns out that was the value sent from the CircleCI orb and I have a [fix](https://github.com/coverallsapp/orb/pull/15) for that.
But on the main build page it states that I am on the master branch, and when I click on the branches dropdown and try to sync, it spins forever. Also the coverage badge shows as unknown!

My repo is private, so wont be able to share that. The language is Node and I am using [nyc](https://github.com/istanbuljs/nyc) to get the test coverage in lcov format. The CI tool used is CircleCI and I am using the [Coveralls orb](https://circleci.com/developer/orbs/orb/coveralls/coveralls#orb-source) to send the data to Coveralls. The code is stored in a Github repository

![Screenshot 2021-11-11 at 16 50 58](https://user-images.githubusercontent.com/13778631/141337115-cf76799a-a111-4511-a60f-d9307c16aa62.png)
As you can see it shows the last build branch being test_coverage (which is correct). It is very small and on the top left of the screenshot. Everywhere else there is a mention to a branch and it is referencing master

In my config for CircleCI I have the following bits;
```
- coveralls/upload:
          parallel: true
          flag_name: Unit Tests
          verbose: true
...
- coveralls/upload:
          parallel: true
          flag_name: Integration Tests
          verbose: true
...
code-coverage-complete:
    docker:
      - image: circleci/node:14.18.1
    steps:
      - coveralls/upload:
          parallel_finished: true
```

I see there is [coveralls-node](https://github.com/nickmerwin/node-coveralls) lib, is that sending the information through the code and not the CI tool. I haven't tried this but think doing it through CI would be better.
