### ISSUE TITLE
Bad response: 422 at public organization repo

### ISSUE THREAD

**Issue by kolosovpetro** [lemurheavy/coveralls-public#1627]
Given:

- Public Github ASP NET Core Web API project at organization: https://github.com/MangoInstantMessenger/MangoMessengerAPI/tree/MANGO-425
- Pipeline with action `Publish coverage report to coveralls.io`: https://github.com/MangoInstantMessenger/MangoMessengerAPI/blob/MANGO-425/.github/workflows/build.yml
```
 - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: MangoAPI.Tests/TestResults/coverage.info
```

- Variable in repository secrets `COVERALLS_REPO_TOKEN` which is got from coveralls dashboard
![image](https://user-images.githubusercontent.com/31904595/161405275-68eb1b2a-2d50-4a09-81a8-34b9bf9ff2f1.png)

The output of the action is: `Error: Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`

Please, clarify. Seems I do everything according to the guide

The pipeline output https://github.com/MangoInstantMessenger/MangoMessengerAPI/runs/5802535642?check_suite_focus=true

**Comment by afinetooth** [comment]
Hi @kolosovpetro.

It looks like you are using the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action), which is one of the only integrations that diverges from the typical pattern of using the `COVERALLS_REPO_TOKEN` to identify your repo to the Coveralls API.

Instead, that integration requires you to pass the `GITHUB_TOKEN` for your repo as its identifier, which, according to the [usage instructions](https://github.com/marketplace/actions/coveralls-github-action#usage) & [examples here](https://github.com/marketplace/actions/coveralls-github-action#standard-example), should be passed as follows:

```
 - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: MangoAPI.Tests/TestResults/coverage.info
```

Try that and let me know if it doesn't work.
