### ISSUE TITLE
"Unknown Commit Message" and "Unknown Commiter" when using GH Actions

### ISSUE THREAD

**Issue by EvHaus** [lemurheavy/coveralls-public#1635]
Hi there,

We're trialing Coveralls. I've set it up via GH Actions using [coveralls-github-action](https://github.com/marketplace/actions/coveralls-github-action) with the following configuration:

```
- name: Coveralls
  continue-on-error: true
  uses: coverallsapp/github-action@master
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    flag-name: kraken-core
```

The coverage report is submitted to Coveralls properly, but some the UI information is not showing up. Specifically the commit message and commiter info. Here's what it ends up looking like in the Coveralls UI:

<img width="1167" alt="Screen Shot 2022-05-12 at 8 31 50 AM" src="https://user-images.githubusercontent.com/226640/168112793-c3aa7a99-981d-4735-b4be-29d4bc39d149.png">

Interestingly, Coveralls correctly picks up the GitHub Actions build link and commit because the links to both of those work great.

Is there something maybe that I forgot to configure to make the rest of the features work as intended?
