### ISSUE TITLE
Coverage showing from branches, but not master

### ISSUE THREAD

**Issue by samullen** [lemurheavy/coveralls-public#1705]
Hi, we have a problem where our coverage report (or at least the increase/decreases) are showing for branches as they are pushed to GitHub, but `master` remains unchanged when those branches are merged.

```
# GitHub Workflow block

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
```

```
# package.json
    "test:coverage": "nyc --silent scripts/tester.sh && nyc --silent scripts/test.sh && nyc merge .nyc_output coverage.json && nyc report",
```

Both test scripts basically evaluate to `./node_modules/.bin/mocha --recursive --colors --reporter dot --no-config "$TEST_PATH"`

```
# .nycrc
{
  "reporter": "lcov"
}
```

Let me know what other information I can provide.
