### ISSUE TITLE
Coverage suddenly became "unknown" from 70%+.

### ISSUE THREAD

**Issue by karan** [lemurheavy/coveralls-public#187]
I pushed some changes today and for some reason my coverage dropped to "unknown".

My .travis.yml file:

```
language: python
python:
    - 2.7
    - 3.3
install: 
    - python setup.py install
    - pip install -r requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors
script:
    - coverage run --source=hn setup.py test
after_success:
    - coveralls
notifications:
  email: false
branches:
  only:
    - master
```

Coverage history: https://coveralls.io/r/karan/HackerNewsAPI

Any pointers?
