### ISSUE TITLE
Go Docs Are Out of Date

### ISSUE THREAD

**Issue by todd** [lemurheavy/coveralls-public#342]
I wasn't able to get a functioning CI build using the information provided in the Go docs alone. The following is what appears to be necessary in `.travis.yml` to get a build to execute properly.

``` yaml
language: go

go:
  - 1.3

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov

env:
  global:
    secure: <Your Encrypted Repo Token Here>

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
```

I'd be more than happy to provide more complete documentation for the website if you guys need/want it.
