### ISSUE TITLE
It seems that coveralls cannot tell merged big size coverage.info file.

### ISSUE THREAD

**Issue by Incarnation-p-lee** [lemurheavy/coveralls-public#810]
I have one coverage test runs twice, run script somewhat as following:

``` bash
#!/bin/bash                                                                                                                                                                                                       

bash ./script/build.sh DEBUG X86_64 LIBC ELF COVERAGE
./output/out/ds.elf -u *.*.*
lcov --directory . --capture --output-file unit_test.info

bash ./script/build.sh RELEASE X86_64 LIBC ELF COVERAGE
./output/out/ds.elf -p=100 *.*.*
lcov --directory . --capture --output-file performance_test.info

lcov --add-tracefile unit_test.info --add-tracefile performance_test.info --output-file coverage.info
cp -v coverage.info /tmp/coverage.info
rm -v *.gcno
```

And the travis.yml config and coveralls link
https://coveralls.io/github/Incarnation-p-lee/libds

``` yml
language: c
compiler:
  - gcc
  - clang
script: 
  - ulimit -s unlimited
  - bash ./script/run_unit_test.sh
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - incarnation.p.lee@outlook.com
install:
  - mkdir lcov && cd lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - cd -
after_success:
  - coveralls-lcov /tmp/coverage.info
  - bash ./script/run_performance_test.sh

```

And the merged coverage.info cannot be detecd by coveralls (but codecov works well). So I have a try with minor running on that repo (Build 118), and it works. But for a full runing, it cannot tell(build 115, 116, 117).

Could u please help to verify it ? thanks in advance!
