### ISSUE TITLE
Go usage is incorrect

### ISSUE THREAD

**Issue by dsoprea** [lemurheavy/coveralls-public#856]
The current documentation shows what's necessary when used with Travis, but it doesn't work.

For a public repository, the following _.travis.yml_ works just fine:

``` yaml
language: go
go: 
  - tip
install:
  - go get -t ./...
  - go get github.com/mattn/goveralls
script:
  - goveralls -service=travis-ci
```

For additional configuration, just refer them to the project page for [goveralls](https://github.com/mattn/goveralls).
